#!/usr/bin/env python3
"""Generate iOS JavaScript with Android's real Java generator (Java 17+).

No production attendance site is contacted. Use --check in CI to detect drift.
"""
import argparse
import pathlib
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Android/app/src/main/java/ch/pfvr/internapp"
OUTPUT = ROOT / "iOS/App/Resources"
HARNESS = r'''
package ch.pfvr.internapp;
import java.nio.file.*;
public class ExportInternalRenderer {
    public static void main(String[] args) throws Exception {
        for (String language : new String[]{"de", "gsw"}) {
            String script = InternalAttendanceSkin.javascript("__BG__", "__CARD__",
                "__SOFT__", "__TEXT__", "__MUTED__", "__BORDER__", "__LINK__",
                language, "__BASE_INTERNAL_URL__");
            // Preserve one theme token resolved by Swift at display time.
            script = script.replace("color-scheme:light!important", "color-scheme:__SCHEME__!important");
            Files.writeString(Path.of(args[0], "internal-attendance-" + language + ".js"),
                "// Generated by tools/internal-export-renderer.py; edit Android source, then regenerate.\n" + script);
        }
    }
}
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="pfvr-internal-renderer-") as directory:
        temporary = pathlib.Path(directory)
        harness = temporary / "ExportInternalRenderer.java"
        harness.write_text(HARNESS)
        subprocess.run(["java", "-m", "jdk.compiler/com.sun.tools.javac.Main", "-encoding", "UTF-8",
                        "-d", directory, str(SOURCE / "InternalAttendanceSkin.java"),
                        str(SOURCE / "UiLanguage.java"), str(harness)], check=True)
        subprocess.run(["java", "-cp", directory, "ch.pfvr.internapp.ExportInternalRenderer", directory], check=True)
        OUTPUT.mkdir(parents=True, exist_ok=True)
        for generated in sorted(temporary.glob("*.js")):
            destination = OUTPUT / generated.name
            if args.check:
                if not destination.exists() or destination.read_bytes() != generated.read_bytes():
                    raise SystemExit(f"Renderer drift: regenerate {destination.relative_to(ROOT)}")
            else:
                destination.write_bytes(generated.read_bytes())
        print("Internal renderer matches Android Java output." if args.check else "Generated German and Swiss German internal renderers.")


if __name__ == "__main__":
    main()
